src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/TriggerFeatureControl__mdt.object-meta.xml
<CustomObject>
    <description>Registers a feature for execution in trigger contexts (before insert, after insert, etc). Only active controls are executed.</description>
    <label>Trigger Feature Control</label>
    <pluralLabel>Trigger Feature Controls</pluralLabel>
</CustomObject>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <description>The exact class name of the handler that implements the TriggerExecutable interface. Set the fully qualified name, if a subclass implements the interface.</description>
    <inlineHelpText>Set the apex class name of the handler that will run in the specified contexts.</inlineHelpText>
    <label>Handler</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Activates the handler for processing.</description>
    <inlineHelpText>Activates the handler. Inactive handlers are only executed with the forceActivateFeature API.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>100</defaultValue>
    <description>The order of execution for this specific handler. Higher numbers are executed later in a transaction.</description>
    <inlineHelpText>Higher priorities are executed later during a transaction. If two handlers have the same priority, their order of execution is random.</inlineHelpText>
    <label>Priority</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/RunOnAfterDelete__c.field-meta.xml
<CustomField>
    <fullName>RunOnAfterDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;after delete&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;after delete&quot; context.</inlineHelpText>
    <label>After Delete</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/RunOnAfterInsert__c.field-meta.xml
<CustomField>
    <fullName>RunOnAfterInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;after insert&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;after insert&quot; context.</inlineHelpText>
    <label>After Insert</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/RunOnAfterUndelete__c.field-meta.xml
<CustomField>
    <fullName>RunOnAfterUndelete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;after undelete&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;after undelete&quot; context.</inlineHelpText>
    <label>After Undelete</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/RunOnAfterUpdate__c.field-meta.xml
<CustomField>
    <fullName>RunOnAfterUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;after update&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;after update&quot; context.</inlineHelpText>
    <label>After Update</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/RunOnBeforeDelete__c.field-meta.xml
<CustomField>
    <fullName>RunOnBeforeDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;before delete&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;before delete&quot; context.</inlineHelpText>
    <label>Before Delete</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/RunOnBeforeInsert__c.field-meta.xml
<CustomField>
    <fullName>RunOnBeforeInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;before insert&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;before insert&quot; context.</inlineHelpText>
    <label>Before Insert</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/RunOnBeforeUpdate__c.field-meta.xml
<CustomField>
    <fullName>RunOnBeforeUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;before update&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;before update&quot; context.</inlineHelpText>
    <label>Before Update</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/SObjectName__c.field-meta.xml
<CustomField>
    <fullName>SObjectName__c</fullName>
    <description>The developer name of the SObject for this control. We do not use a Metadata Relationship for performance reasons (30 ms vs 600 ms loading times).</description>
    <inlineHelpText>Set the SObject where the handler is executed. The SObject must implement a trigger that calls the framework.</inlineHelpText>
    <label>SObject Name</label>
    <length>43</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/packaged/trigger-framework/default/classes/TriggerControlsRepository.cls
public without sharing class TriggerControlsRepository {
    private static Map<String, List<TriggerFeatureControl__mdt>> mocks = new Map<String, List<TriggerFeatureControl__mdt>>();

    @testVisible
    private static void setMocks(String sobjectName, List<TriggerFeatureControl__mdt> mockControls) {
        mocks.put(sobjectName, mockControls);
    }

    public static List<TriggerFeatureControl__mdt> getControls(String sobjectName) {
        if (Test.isRunningTest() && mocks.containsKey(sobjectName)) {
            return mocks.get(sobjectName);
        }
        return [
            SELECT
                Id,
                DeveloperName,
                Handler__c,
                IsActive__c,
                Priority__c,
                RunOnAfterDelete__c,
                RunOnAfterInsert__c,
                RunOnAfterUndelete__c,
                RunOnAfterUpdate__c,
                RunOnBeforeDelete__c,
                RunOnBeforeInsert__c,
                RunOnBeforeUpdate__c
            FROM TriggerFeatureControl__mdt
            WHERE SObjectName__c = :sobjectName
            ORDER BY Priority__c ASC
        ];
    }
}