src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/TriggerFeatureControl__mdt.object-meta.xml
<CustomObject>
    <description>Registers a feature for execution in trigger contexts (before insert, after insert, etc). Only active controls are executed.</description>
    <label>Trigger Feature Control</label>
    <pluralLabel>Trigger Feature Controls</pluralLabel>
</CustomObject>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <description>The exact class name of the handler that implements the TriggerExecutable interface. Set the fully qualified name, if a subclass implements the interface.</description>
    <inlineHelpText>Set the apex class name of the handler that will run in the specified contexts.</inlineHelpText>
    <label>Handler</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Activates the handler for processing.</description>
    <inlineHelpText>Activates the handler. Inactive handlers are only executed with the forceActivateFeature API.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>100</defaultValue>
    <description>The order of execution for this specific handler. Higher numbers are executed later in a transaction.</description>
    <inlineHelpText>Higher priorities are executed later during a transaction. If two handlers have the same priority, their order of execution is random.</inlineHelpText>
    <label>Priority</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/RunOnAfterDelete__c.field-meta.xml
<CustomField>
    <fullName>RunOnAfterDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;after delete&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;after delete&quot; context.</inlineHelpText>
    <label>After Delete</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/RunOnAfterInsert__c.field-meta.xml
<CustomField>
    <fullName>RunOnAfterInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;after insert&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;after insert&quot; context.</inlineHelpText>
    <label>After Insert</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/RunOnAfterUndelete__c.field-meta.xml
<CustomField>
    <fullName>RunOnAfterUndelete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;after undelete&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;after undelete&quot; context.</inlineHelpText>
    <label>After Undelete</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/RunOnAfterUpdate__c.field-meta.xml
<CustomField>
    <fullName>RunOnAfterUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;after update&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;after update&quot; context.</inlineHelpText>
    <label>After Update</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/RunOnBeforeDelete__c.field-meta.xml
<CustomField>
    <fullName>RunOnBeforeDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;before delete&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;before delete&quot; context.</inlineHelpText>
    <label>Before Delete</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/RunOnBeforeInsert__c.field-meta.xml
<CustomField>
    <fullName>RunOnBeforeInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;before insert&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;before insert&quot; context.</inlineHelpText>
    <label>Before Insert</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/trigger-framework/default/objects/TriggerFeatureControl__mdt/fields/RunOnBeforeUpdate__c.field-meta.xml
<CustomField>
    <fullName>RunOnBeforeUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Runs this handler in &quot;before update&quot; context.</description>
    <inlineHelpText>Runs the handler in &quot;before update&quot; context.</inlineHelpText>
    <label>Before Update</label>
    <type>Checkbox</type>
</CustomField>

src/packaged/trigger-framework/test/classes/TriggersMocks.cls
@isTest
public class TriggersMocks {
    public static TriggerFeatureControl__mdt makeTriggerControl(String developerName, String triggerHandler) {
        return new TriggerFeatureControl__mdt(
            DeveloperName = developerName,
            Handler__c = triggerHandler,
            IsActive__c = true,
            Priority__c = 100,
            RunOnAfterDelete__c = false,
            RunOnAfterInsert__c = false,
            RunOnAfterUndelete__c = false,
            RunOnAfterUpdate__c = false,
            RunOnBeforeDelete__c = false,
            RunOnBeforeInsert__c = false,
            RunOnBeforeUpdate__c = false
        );
    }
}