src/packaged/visualforce-utils/doc-labels/objects/DocumentLabel__c/DocumentLabel__c.object-meta.xml
<CustomObject>
    <description>Manage and translate custom labels for PDF documents. After a developer integrated document labels in their Visualforce pages, you can translate safely translate them.</description>
    <label>Document Label</label>
    <nameField>
        <label>Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Labels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/packaged/visualforce-utils/doc-labels/objects/DocumentLabel__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DocumentLanguages</valueSetName>
    </valueSet>
</CustomField>

src/packaged/visualforce-utils/doc-labels/objects/DocumentLabelTranslation__c/DocumentLabelTranslation__c.object-meta.xml
<CustomObject>
    <description>Translations for custom document labels</description>
    <label>Document Label Translation</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Label Translations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/packaged/visualforce-utils/doc-labels/objects/DocumentLabelTranslation__c/fields/MasterLabel__c.field-meta.xml
<CustomField>
    <fullName>MasterLabel__c</fullName>
    <label>Master Label</label>
    <referenceTo>DocumentLabel__c</referenceTo>
    <relationshipLabel>Document Label Translations</relationshipLabel>
    <relationshipName>Translations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/packaged/visualforce-utils/doc-labels/objects/DocumentLabelTranslation__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/packaged/visualforce-utils/doc-labels/globalValueSets/DocumentLanguages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>de_DE</fullName>
        <label>Deutsch (Deutschland)</label>
    </customValue>
    <customValue>
        <fullName>en_US</fullName>
        <default>true</default>
        <label>English (USA)</label>
    </customValue>
    <description>Language codes or names to localise documents with custom labels and text components. Subscriber orgs can manage all available values.</description>
    <masterLabel>Document Languages</masterLabel>
</GlobalValueSet>

src/packaged/visualforce-utils/doc-labels/classes/DocumentLabels.cls
public class DocumentLabels {
    private static Map<String, DocumentLabel> labels {
        get {
            if (labels == null) {
                labels = new Map<String, DocumentLabel>();
                for (DocumentLabel__c dl : [
                    SELECT Id, Name, Language__c, (SELECT Id, Language__c, Value__c FROM Translations__r)
                    FROM DocumentLabel__c
                ]) {
                    labels.put(dl.Name, new DocumentLabel(dl));
                }
            }
            return labels;
        }
        set;
    }

    public static String getTranslation(String masterLabel, String languageCode) {
        if (labels.containsKey(masterLabel)) {
            return labels.get(masterLabel).translate(languageCode);
        }
        return masterLabel;
    }
}