src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/Currency__mdt.object-meta.xml
<CustomObject>
    <description>Advanced formatting and behavior configurations for org currencies. Augments the standard currency object.</description>
    <label>Currency</label>
    <pluralLabel>Currencies</pluralLabel>
</CustomObject>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/CodePosition__c.field-meta.xml
<CustomField>
    <fullName>CodePosition__c</fullName>
    <description>Position of the currency ISO code when rendered in Apex or Visualforce</description>
    <inlineHelpText>Specifies where the ISO code is displayed. BEFORE the numeric value (USD 123.00) or AFTER it (123.00 USD)</inlineHelpText>
    <label>Currency Code Position</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BEFORE</fullName>
                <default>true</default>
                <label>Before</label>
            </value>
            <value>
                <fullName>AFTER</fullName>
                <label>After</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/DecimalSeparator__c.field-meta.xml
<CustomField>
    <fullName>DecimalSeparator__c</fullName>
    <description>Separator for currencies with decimal places</description>
    <inlineHelpText>Specify the separator for the numeric value. Only effective for currencies with more than 0 decimal places.</inlineHelpText>
    <label>Decimal Separator</label>
    <length>1</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/FormatLength__c.field-meta.xml
<CustomField>
    <fullName>FormatLength__c</fullName>
    <description>The default format length that is used when formatting this currency.</description>
    <inlineHelpText>Provide the default format mode that is used, when the currency is formatted. Short only prints the symbol, Medium prints ISO code and Explicit prints symbol and ISO code.</inlineHelpText>
    <label>Format Length</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SYMBOL</fullName>
                <default>true</default>
                <label>Symbol</label>
            </value>
            <value>
                <fullName>ISO_CODE</fullName>
                <label>ISO Code</label>
            </value>
            <value>
                <fullName>EXPLICIT</fullName>
                <label>Explicit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/Symbol__c.field-meta.xml
<CustomField>
    <fullName>Symbol__c</fullName>
    <description>Currency symbol or abbreviation for the currency according to ISO 4217.</description>
    <inlineHelpText>Provide the symbol or abbreviation for the currency. Rendered in short and explicit format length.</inlineHelpText>
    <label>Currency Symbol</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/SymbolPosition__c.field-meta.xml
<CustomField>
    <fullName>SymbolPosition__c</fullName>
    <description>Position of the symbol when rendering short or explicit format</description>
    <inlineHelpText>Position of the symbol when rendering short or explicit format. Symbols before a numeric value are shown without spaces (in compliance with ISO-4217).</inlineHelpText>
    <label>Currency Symbol Position</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BEFORE</fullName>
                <default>true</default>
                <label>Before</label>
            </value>
            <value>
                <fullName>AFTER</fullName>
                <label>After</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/ThousandsSeparator__c.field-meta.xml
<CustomField>
    <fullName>ThousandsSeparator__c</fullName>
    <label>Thousands Separator</label>
    <length>1</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/classes/Test_Unit_Currencies.cls
@isTest
public class Test_Unit_Currencies {
    @isTest
    static void format_UnconfiguredCurrencyIsoCode_ThrowsException() {
        // Assert
        try {
            String output = Currencies.format('ABC', 1234);
            System.Assert.fail('Expected exception, but continued.');
        } catch (IllegalArgumentException iae) {
            String expectedMsg = String.format(System.Label.Invalid_Currency_Iso_Code_Unknown_Custom_Metadata, new List<Object>{ 'ABC' });
            System.Assert.areEqual(expectedMsg, iae.getMessage(), 'exception message');
        }
    }

    @isTest
    static void format_UserDefaultCurrency_FormatsToConfig() {
        // Arrange
        String testCurrencyCode = UserInfo.getDefaultCurrency();
        Currency__mdt userDefaultMock = makeDefaultMock(testCurrencyCode);
        Currencies.setMockCurrencyConfiguration(userDefaultMock);

        // Act & Assert
        Map<Decimal, String> inputOutputs = new Map<Decimal, String>{
            0.00 => '0,00 €',
            0.05 => '0,05 €',
            0.50 => '0,50 €',
            0.99 => '0,99 €',
            0.99999 => '1,00 €',
            1.00 => '1,00 €',
            1.1 => '1,10 €',
            1.10 => '1,10 €',
            1.01 => '1,01 €',
            1.509 => '1,51 €',
            999.99 => '999,99 €',
            1000.00 => '1.000,00 €',
            1000000.00 => '1.000.000,00 €'
        };
        for (Decimal inputValue : inputOutputs.keySet()) {
            System.Assert.areEqual(
                inputOutputs.get(inputValue),
                Currencies.format(testCurrencyCode, inputValue),
                'output matches expected'
            );
        }
    }

    static Currency__mdt makeDefaultMock(String isoCode) {
        return new Currency__mdt(
            DeveloperName = isoCode,
            Label = 'Test Currency',
            CodePosition__c = 'BEFORE',
            SymbolPosition__c = 'AFTER',
            DecimalSeparator__c = ',',
            ThousandsSeparator__c = '.',
            FormatLength__c = 'SYMBOL',
            Symbol__c = '€'
        );
    }
}