src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/Currency__mdt.object-meta.xml
<CustomObject>
    <description>Advanced formatting and behavior configurations for org currencies. Augments the standard currency object.</description>
    <label>Currency</label>
    <pluralLabel>Currencies</pluralLabel>
</CustomObject>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/CodePosition__c.field-meta.xml
<CustomField>
    <fullName>CodePosition__c</fullName>
    <description>Position of the currency ISO code when rendered in Apex or Visualforce</description>
    <inlineHelpText>Specifies where the ISO code is displayed. BEFORE the numeric value (USD 123.00) or AFTER it (123.00 USD)</inlineHelpText>
    <label>Currency Code Position</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BEFORE</fullName>
                <default>true</default>
                <label>Before</label>
            </value>
            <value>
                <fullName>AFTER</fullName>
                <label>After</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/DecimalSeparator__c.field-meta.xml
<CustomField>
    <fullName>DecimalSeparator__c</fullName>
    <description>Separator for currencies with decimal places</description>
    <inlineHelpText>Specify the separator for the numeric value. Only effective for currencies with more than 0 decimal places.</inlineHelpText>
    <label>Decimal Separator</label>
    <length>1</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/FormatLength__c.field-meta.xml
<CustomField>
    <fullName>FormatLength__c</fullName>
    <description>The default format length that is used when formatting this currency.</description>
    <inlineHelpText>Provide the default format mode that is used, when the currency is formatted. Short only prints the symbol, Medium prints ISO code and Explicit prints symbol and ISO code.</inlineHelpText>
    <label>Format Length</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SYMBOL</fullName>
                <default>true</default>
                <label>Symbol</label>
            </value>
            <value>
                <fullName>ISO_CODE</fullName>
                <label>ISO Code</label>
            </value>
            <value>
                <fullName>EXPLICIT</fullName>
                <label>Explicit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/Symbol__c.field-meta.xml
<CustomField>
    <fullName>Symbol__c</fullName>
    <description>Currency symbol or abbreviation for the currency according to ISO 4217.</description>
    <inlineHelpText>Provide the symbol or abbreviation for the currency. Rendered in short and explicit format length.</inlineHelpText>
    <label>Currency Symbol</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/SymbolPosition__c.field-meta.xml
<CustomField>
    <fullName>SymbolPosition__c</fullName>
    <description>Position of the symbol when rendering short or explicit format</description>
    <inlineHelpText>Position of the symbol when rendering short or explicit format. Symbols before a numeric value are shown without spaces (in compliance with ISO-4217).</inlineHelpText>
    <label>Currency Symbol Position</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BEFORE</fullName>
                <default>true</default>
                <label>Before</label>
            </value>
            <value>
                <fullName>AFTER</fullName>
                <label>After</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/ThousandsSeparator__c.field-meta.xml
<CustomField>
    <fullName>ThousandsSeparator__c</fullName>
    <label>Thousands Separator</label>
    <length>1</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/classes/CurrencyTypeExtension.cls
/**
 * Represents a currency like `USD` or `EUR` and provides various methods
 * to format decimals with that currency.
 *
 * @group Visualforce Utilities
 */
public class CurrencyTypeExtension {
    String isoCode;
    Currency__mdt config;
    CurrencyFormatLength formattingStyle;
    Formatter valueFormatter;

    /**
     * Do not construct directly. Use the factory method in `Currencies`.
     */
    public CurrencyTypeExtension(String isoCode, Currency__mdt cmd) {
        this.config = cmd;
        if (this.config == null) {
            throw new IllegalArgumentException(
                String.format(System.Label.Invalid_Currency_Iso_Code_Unknown_Custom_Metadata, new List<Object>{ isoCode })
            );
        }
        this.setFormattingStyle(CurrencyFormatLength.valueOf(this.config.FormatLength__c));
    }

    //                 PUBLIC

    /**
     * Formats the input with the default formatting style from config.
     *
     * @param value
     * @return  `String`
     */
    public String format(Decimal value) {
        return this.valueFormatter.format(value);
    }

    /**
     * Formats the input with a custom formatting style.
     *
     * @param value
     * @param formattingStyle
     * @return  `String`
     */
    public String format(Decimal value, CurrencyFormatLength formattingStyle) {
        Formatter f = this.makeFormatter(formattingStyle);
        return f.format(value);
    }

    /**
     * Returns the currency Iso Code.
     *
     * @return  `String`
     */
    public String getIsoCode() {
        return this.config.DeveloperName;
    }

    /**
     * Sets the formatting style for all future calls to `format`.
     *
     * @param formattingStyle
     * @return  `CurrencyTypeExtension`
     */
    public CurrencyTypeExtension setFormattingStyle(CurrencyFormatLength formattingStyle) {
        this.formattingStyle = formattingStyle;
        this.valueFormatter = this.makeFormatter(formattingStyle);
        return this;
    }

    public String getSymbol() {
        return this.config.Symbol__c;
    }

    public String getSymbolPosition() {
        return this.config.SymbolPosition__c;
    }

    public String getCodePosition() {
        return this.config.CodePosition__c;
    }

    public CurrencyFormatLength getFormattingStyle() {
        return this.formattingStyle;
    }

    //                  PRIVATE ZONE

    private Formatter makeFormatter(CurrencyFormatLength style) {
        Formatter f;
        switch on style {
            when SYMBOL {
                f = new ShortStyleFormatter();
            }
            when ISO_CODE {
                f = new IsoStyleFormatter();
            }
            when else {
                f = new ExplicitStyleFormatter();
            }
        }
        f.symbolBeforeNumber = this.config.SymbolPosition__c == 'BEFORE';
        f.codeBeforeNumber = this.config.CodePosition__c == 'BEFORE';
        f.isoCode = this.config.DeveloperName;
        f.symbol = this.config.Symbol__c;
        f.decimalSeparator = this.config.DecimalSeparator__c;
        f.thousandSeparator = this.config.ThousandsSeparator__c;
        f.scale = OrgCurrencyConfiguration.getDecimalPlaces(this.config.DeveloperName);
        return f;
    }

    private abstract class Formatter {
        public Boolean symbolBeforeNumber;
        public Boolean codeBeforeNumber;
        public String isoCode;
        public String symbol;
        public String decimalSeparator;
        public String thousandSeparator;
        public Integer scale;

        public abstract String format(Decimal value);

        private String formatNumber(Decimal value) {
            Decimal roundedValue = value.setScale(this.scale, System.RoundingMode.HALF_UP);
            if (this.scale > 0) {
                return String.format(
                    '{0}{1}{2}',
                    new List<Object>{
                        this.formatIntLiteral(roundedValue),
                        this.decimalSeparator,
                        this.formatPrecisionLiteral(roundedValue)
                    }
                );
            } else {
                return this.formatIntLiteral(roundedValue);
            }
        }

        private String formatPrecisionLiteral(Decimal value) {
            Integer precisionValue = Integer.valueOf((value.abs() - value.abs().intValue()) * Math.pow(10, this.scale));
            if (precisionValue.format().length() < this.scale) {
                return precisionValue.format().leftPad(this.scale, '0');
            } else {
                return precisionValue.format().left(this.scale);
            }
        }

        private String formatIntLiteral(Decimal value) {
            return value.abs().intValue().format().replaceAll('(\\.|,| |’)', this.thousandSeparator);
        }

        public String formatSign(Decimal value) {
            return value >= 0 ? '' : '-';
        }
    }

    private class ShortStyleFormatter extends Formatter {
        public override String format(Decimal value) {
            if (this.symbolBeforeNumber) {
                return String.format('{0}{1}{2}', new List<Object>{ this.formatSign(value), this.symbol, this.formatNumber(value) });
            } else {
                return String.format('{0}{1} {2}', new List<Object>{ this.formatSign(value), this.formatNumber(value), this.symbol });
            }
        }
    }

    private class IsoStyleFormatter extends Formatter {
        public override String format(Decimal value) {
            if (this.codeBeforeNumber) {
                return String.format('{0} {1}{2}', new List<Object>{ this.isoCode, this.formatSign(value), this.formatNumber(value) });
            } else {
                return String.format('{0}{1} {2}', new List<Object>{ this.formatSign(value), this.formatNumber(value), this.isoCode });
            }
        }
    }

    private class ExplicitStyleFormatter extends Formatter {
        public override String format(Decimal value) {
            String shortFormatted;
            if (this.symbolBeforeNumber) {
                shortFormatted = String.format(
                    '{0}{1}{2}',
                    new List<Object>{ this.formatSign(value), this.symbol, this.formatNumber(value) }
                );
            } else {
                shortFormatted = String.format(
                    '{0}{1} {2}',
                    new List<Object>{ this.formatSign(value), this.formatNumber(value), this.symbol }
                );
            }
            if (this.codeBeforeNumber) {
                return String.format('{0} {1}', new List<Object>{ this.isoCode, shortFormatted });
            } else {
                return String.format('{0} {1}', new List<Object>{ shortFormatted, this.isoCode });
            }
        }
    }
}