src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/Currency__mdt.object-meta.xml
<CustomObject>
    <description>Advanced formatting and behavior configurations for org currencies. Augments the standard currency object.</description>
    <label>Currency</label>
    <pluralLabel>Currencies</pluralLabel>
</CustomObject>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/CurrencyCodePosition__c.field-meta.xml
<CustomField>
    <fullName>CurrencyCodePosition__c</fullName>
    <label>Currency Code Position</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BEFORE</fullName>
                <default>true</default>
                <label>Before</label>
            </value>
            <value>
                <fullName>AFTER</fullName>
                <label>After</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/CurrencySymbol__c.field-meta.xml
<CustomField>
    <fullName>CurrencySymbol__c</fullName>
    <description>Currency symbol or abbreviation for the currency according to ISO 4217.</description>
    <inlineHelpText>Provide the symbol or abbreviation for the currency. This is shown in short and explicit format length.</inlineHelpText>
    <label>Currency Symbol</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/CurrencySymbolPosition__c.field-meta.xml
<CustomField>
    <fullName>CurrencySymbolPosition__c</fullName>
    <label>Currency Symbol Position</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BEFORE</fullName>
                <default>true</default>
                <label>Before</label>
            </value>
            <value>
                <fullName>AFTER</fullName>
                <label>After</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/DecimalSeparator__c.field-meta.xml
<CustomField>
    <fullName>DecimalSeparator__c</fullName>
    <description>Separator for currencies with decimal places</description>
    <inlineHelpText>Specify the separator for the numeric value. Only effective for currencies with more than 0 decimal places.</inlineHelpText>
    <label>Decimal Separator</label>
    <length>1</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/FormatLength__c.field-meta.xml
<CustomField>
    <fullName>FormatLength__c</fullName>
    <description>The default format length that is used when formatting this currency.</description>
    <inlineHelpText>Provide the default format mode that is used, when the currency is formatted. Short only prints the symbol, Medium prints ISO code and Explicit prints symbol and ISO code.</inlineHelpText>
    <label>Format Length</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SYMBOL</fullName>
                <default>true</default>
                <label>Symbol</label>
            </value>
            <value>
                <fullName>ISO_CODE</fullName>
                <label>ISO Code</label>
            </value>
            <value>
                <fullName>EXPLICIT</fullName>
                <label>Explicit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/NativeLocale__c.field-meta.xml
<CustomField>
    <fullName>NativeLocale__c</fullName>
    <description>The native locale of the country where this currency is the legal currency.</description>
    <inlineHelpText>Provide the default locale that is used to format this currency (e.g. en_US)</inlineHelpText>
    <label>Native Locale</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/objects/Currency__mdt/fields/ThousandsSeparator__c.field-meta.xml
<CustomField>
    <fullName>ThousandsSeparator__c</fullName>
    <label>Thousands Separator</label>
    <length>1</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/packaged/visualforce-utils/currency-formatter/classes/CurrencyValue.cls
public class CurrencyValue {
    String isoCode;
    Currency__mdt config;
    CurrencyType currType;
    Decimal value;
    FormatLength formattingStyle;
    Formatter valueFormatter;

    public enum FormatLength {
        SHORT_FORMAT,
        ISO_FORMAT,
        EXPLICIT_FORMAT
    }

    public CurrencyValue(String isoCode, Decimal value) {
        this.isoCode = isoCode;
        this.currType = CurrencyTypeRepository.Values.get(isoCode);
        if (this.currType == null) {
            throw new IllegalArgumentException(
                String.format(System.Label.Invalid_Currency_Iso_Code_Unknown_Currency_Type, new List<Object>{ isoCode })
            );
        }
        this.config = Currency__mdt.getInstance(this.isoCode);
        if (this.config == null) {
            throw new IllegalArgumentException(
                String.format(System.Label.Invalid_Currency_Iso_Code_Unknown_Custom_Metadata, new List<Object>{ isoCode })
            );
        }
        this.value = value.setScale(this.currType.DecimalPlaces, RoundingMode.HALF_UP);
        this.setFormattingStyle(CurrencyValue.FormatLength.valueOf(this.config.FormatLength__c));
    }

    //                 PUBLIC STATIC

    public static String format(String isoCode, Decimal value) {
        return new CurrencyValue(isoCode, value).format();
    }

    public static String format(String isoCode, Decimal value, FormatLength formattingStyle) {
        return new CurrencyValue(isoCode, value).setFormattingStyle(formattingStyle).format();
    }

    //                    PUBLIC

    public CurrencyValue setFormattingStyle(CurrencyValue.FormatLength formattingStyle) {
        this.formattingStyle = formattingStyle;
        switch on this.formattingStyle {
            when SHORT_FORMAT {
                this.valueFormatter = new ShortStyleFormatter();
            }
            when ISO_FORMAT {
                this.valueFormatter = new IsoStyleFormatter();
            }
            when else {
                this.valueFormatter = new ExplicitStyleFormatter();
            }
        }
        this.valueFormatter.symbolBeforeNumber = this.config.CurrencySymbolPosition__c == 'BEFORE';
        this.valueFormatter.codeBeforeNumber = this.config.CurrencyCodePosition__c == 'BEFORE';
        this.valueFormatter.isoCode = this.isoCode;
        this.valueFormatter.symbol = this.config.CurrencySymbol__c;
        this.valueFormatter.decimalSeparator = this.config.DecimalSeparator__c;
        this.valueFormatter.thousandSeparator = this.config.ThousandsSeparator__c;
        this.valueFormatter.scale = this.currType.DecimalPlaces;
        return this;
    }

    public String format() {
        return this.valueFormatter.format(this.value);
    }

    public Decimal getAbsoluteValue() {
        return this.value.abs();
    }

    public String getSign() {
        return this.value >= 0 ? '' : '-';
    }

    public String getDefaultLocale() {
        return this.config.NativeLocale__c;
    }

    public String getSymbol() {
        return this.config.CurrencySymbol__c;
    }

    public String getSymbolPosition() {
        return this.config.CurrencySymbolPosition__c;
    }

    public String getCodePosition() {
        return this.config.CurrencyCodePosition__c;
    }

    public FormatLength getFormattingStyle() {
        return this.formattingStyle;
    }

    //                  PRIVATE ZONE

    private abstract class Formatter {
        public Boolean symbolBeforeNumber;
        public Boolean codeBeforeNumber;
        public String isoCode;
        public String symbol;
        public String decimalSeparator;
        public String thousandSeparator;
        public Integer scale;

        public abstract String format(Decimal value);

        private String formatNumber(Decimal value) {
            if (this.scale > 0) {
                return String.format(
                    '{0}{1}{2}',
                    new List<Object>{ this.formatIntLiteral(value), this.decimalSeparator, this.formatPrecisionLiteral(value) }
                );
            } else {
                return this.formatIntLiteral(value);
            }
        }

        private String formatPrecisionLiteral(Decimal value) {
            Integer precisionValue = Integer.valueOf((value.abs() - value.abs().intValue()) * Math.pow(10, this.scale));
            if (precisionValue.format().length() < this.scale) {
                return precisionValue.format().leftPad(this.scale, '0');
            } else {
                return precisionValue.format().left(this.scale);
            }
        }

        private String formatIntLiteral(Decimal value) {
            return value.abs().intValue().format().replaceAll('(\\.|,| |’)', this.thousandSeparator);
        }

        public String formatSign(Decimal value) {
            return value >= 0 ? '' : '-';
        }
    }

    private class ShortStyleFormatter extends Formatter {
        public override String format(Decimal value) {
            if (this.symbolBeforeNumber) {
                return String.format('{0}{1}{2}', new List<Object>{ this.formatSign(value), this.symbol, this.formatNumber(value) });
            } else {
                return String.format('{0}{1} {2}', new List<Object>{ this.formatSign(value), this.formatNumber(value), this.symbol });
            }
        }
    }

    private class IsoStyleFormatter extends Formatter {
        public override String format(Decimal value) {
            if (this.codeBeforeNumber) {
                return String.format('{0} {1}{2}', new List<Object>{ this.isoCode, this.formatSign(value), this.formatNumber(value) });
            } else {
                return String.format('{0}{1} {2}', new List<Object>{ this.formatSign(value), this.formatNumber(value), this.isoCode });
            }
        }
    }

    private class ExplicitStyleFormatter extends Formatter {
        public override String format(Decimal value) {
            String shortFormatted;
            if (this.symbolBeforeNumber) {
                shortFormatted = String.format(
                    '{0}{1}{2}',
                    new List<Object>{ this.formatSign(value), this.symbol, this.formatNumber(value) }
                );
            } else {
                shortFormatted = String.format(
                    '{0}{1} {2}',
                    new List<Object>{ this.formatSign(value), this.formatNumber(value), this.symbol }
                );
            }
            if (this.codeBeforeNumber) {
                return String.format('{0} {1}', new List<Object>{ this.isoCode, shortFormatted });
            } else {
                return String.format('{0} {1}', new List<Object>{ shortFormatted, this.isoCode });
            }
        }
    }
}